AWSTemplateFormatVersion: "2010-09-09"
Description: IAM Roles for AWS Textract Workflow

Resources:
  # IAM Role for Lambda Execution
  TextractLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: TextractLambdaExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: TextractPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              # Allow Lambda to read from the upload bucket
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Sub "arn:aws:s3:::${TextractUploadBucketName}-${AWS::AccountId}-${AWS::Region}/*"
              # Allow Lambda to write to the DynamoDB table
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoDBTableName}"
              # Allow Lambda to call Textract
              - Effect: Allow
                Action:
                  - textract:AnalyzeDocument
                Resource: "*"
              # Allow Lambda to write logs to CloudWatch
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "arn:aws:logs:*:*:*"

Parameters:
  TextractUploadBucketName:
    Type: String
    Description: Name of the S3 bucket where files are uploaded for processing
  DynamoDBTableName:
    Type: String
    Description: Name of the DynamoDB table for storing extracted data