AWSTemplateFormatVersion: "2010-09-09"
Description: IAM Roles for AWS Textract Workflow

Resources:
  # IAM Role for Lambda Execution
  TextractLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: TextractLambdaExecutionRole  # Static name for the IAM role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: TextractPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              # Allow Lambda to read from the S3 upload bucket
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: "arn:aws:s3:::textract-upload-bucket/*"

              # Allow Lambda to write to the DynamoDB table
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                Resource: "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/TextractDataTable"

              # Allow Lambda to use Textract
              - Effect: Allow
                Action:
                  - textract:AnalyzeDocument
                Resource: "*"

              # Allow Lambda to write logs to CloudWatch
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*"

Outputs:
  TextractLambdaExecutionRoleArn:
    Description: ARN of the Lambda execution role
    Value: !GetAtt TextractLambdaExecutionRole.Arn
    Export:
      Name: TextractLambdaExecutionRoleArn