AWSTemplateFormatVersion: "2010-09-09"
Description: AWS Textract Workflow Resources

Resources:
  # S3 Bucket for Lambda Code
  LambdaCodeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: textract-lambda-code-bucket  # Static name for the Lambda code bucket

  # S3 Bucket for Uploads (Triggers Lambda)
  TextractUploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: textract-upload-bucket  # Static name for the upload bucket
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: "s3:ObjectCreated:*"
            Function: !GetAtt TextractFunction.Arn

  # DynamoDB Table for Storing Extracted Data
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TextractDataTable  # Static name for the DynamoDB table
      AttributeDefinitions:
        - AttributeName: DocumentId
          AttributeType: S
      KeySchema:
        - AttributeName: DocumentId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  # Lambda Function for Processing S3 Events
  TextractFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: TextractFunction  # Static name for the Lambda function
      Runtime: python3.8
      Role: !ImportValue TextractLambdaExecutionRoleArn
      Handler: lambda_function.lambda_handler
      Code:
        S3Bucket: textract-lambda-code-bucket  # Static name for the Lambda code bucket
        S3Key: lambda_function.zip
      Timeout: 300
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: TextractDataTable  # Static name for the DynamoDB table

  # Permission for S3 to Invoke Lambda
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref TextractFunction
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !GetAtt TextractUploadBucket.Arn