AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS Textract Workflow Infrastructure"

Parameters:
  AccountId:
    Type: String
    Description: AWS Account ID

Resources:
  # S3 Buckets
  TextractSourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "textract-source-${AWS::AccountId}"
      
  TextractLambdaCodeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "textract-lambda-code-bucket-${AWS::AccountId}"

  # DynamoDB Table
  TextractDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TextractDataTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: DocumentId
          AttributeType: S
      KeySchema:
        - AttributeName: DocumentId
          KeyType: HASH

  # IAM Role
  TextractLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: TextractLambdaExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: TextractPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - textract:*
                  - s3:GetObject
                  - s3:PutObject
                  - dynamodb:PutItem
                Resource: 
                  - !Sub "arn:aws:s3:::textract-source-${AWS::AccountId}/*"
                  - !Sub "arn:aws:s3:::textract-lambda-code-bucket-${AWS::AccountId}/*"
                  - !GetAtt TextractDataTable.Arn

  # Lambda Function
  TextractFunction:
    Type: AWS::Lambda::Function
    DependsOn: 
      - TextractLambdaCodeBucket
      - TextractLambdaExecutionRole
    Properties:
      FunctionName: TextractFunction
      Runtime: python3.8
      Handler: lambda_function.lambda_handler
      Role: !GetAtt TextractLambdaExecutionRole.Arn
      Code:
        S3Bucket: !Sub "textract-lambda-code-bucket-${AWS::AccountId}"
        S3Key: lambda_function.zip
      Environment:
        Variables:
          SOURCE_BUCKET: !Ref TextractSourceBucket
          DYNAMODB_TABLE: !Ref TextractDataTable
      Timeout: 300
      MemorySize: 256

Outputs:
  SourceBucketName:
    Description: Name of the source S3 bucket
    Value: !Ref TextractSourceBucket

  LambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt TextractFunction.Arn

  DynamoDBTableName:
    Description: Name of the DynamoDB table
    Value: !Ref TextractDataTable