AWSTemplateFormatVersion: '2010-09-09'
Description: S3 infrastructure for Textract service

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket

Resources:
  LambdaCodeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled

Outputs:
  BucketName:
    Description: Name of the created S3 bucket
    Value: !Ref LambdaCodeBucket