AWSTemplateFormatVersion: '2010-09-09'
Description: S3 infrastructure for Textract service

Resources:
  LambdaCodeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: textract-lambda-code-bucket-2024
      VersioningConfiguration:
        Status: Enabled

  SourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: textract-source-docs-2024

Outputs:
  LambdaCodeBucketName:
    Description: Name of the Lambda code bucket
    Value: !Ref LambdaCodeBucket
  SourceBucketName:
    Description: Name of the source bucket
    Value: !Ref SourceBucket