AWSTemplateFormatVersion: '2010-09-09'
Description: Textract service infrastructure

Parameters:
  AccountId:
    Type: String
    Description: AWS Account ID
  BucketName:
    Type: String
    Description: S3 bucket containing Lambda code

Resources:
  TextractFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub textract-function-${AccountId}
      Runtime: python3.8
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref BucketName
        S3Key: lambda_function.zip
      Timeout: 30

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole