AWSTemplateFormatVersion: '2010-09-09'
Description: Textract service infrastructure

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: textract-lambda-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: TextractAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - textract:*
                  - s3:GetObject
                  - s3:PutBucketNotification
                  - s3:GetBucketNotification
                Resource: 
                  - arn:aws:s3:::textract-source-docs-2025/*
                  - arn:aws:s3:::textract-source-docs-2025

  TextractFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: TextractFunction
      Runtime: python3.8
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: textract-lambda-code-bucket-2025
        S3Key: lambda_function.zip
      Environment:
        Variables:
          SOURCE_BUCKET: textract-source-docs-2025
      Timeout: 300