name: Deploy S3

on:
  workflow_call:
    outputs:
      bucket_name:
        description: "S3 bucket name"
        value: ${{ jobs.deploy.outputs.bucket_name }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      bucket_name: ${{ steps.bucket.outputs.name }}
    
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set AWS Account ID
        run: echo "AWS_ACCOUNT_ID=$(aws sts get-caller-identity --output text --query Account)" >> $GITHUB_ENV

      - name: Deploy S3
        run: |
          aws cloudformation deploy \
            --stack-name textract-s3 \
            --template-file templates/s3.yaml \
            --parameter-overrides \
              AccountId=${AWS_ACCOUNT_ID}

      - id: bucket
        name: Get bucket name
        run: |
          echo "name=textract-lambda-code-${AWS_ACCOUNT_ID}" >> $GITHUB_OUTPUT