name: AWS Textract Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy AWS Resources
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: Create S3 Bucket for Lambda Code
      - name: Create S3 Bucket for Lambda Code
        run: |
          LAMBDA_CODE_BUCKET="textract-lambda-code-bucket"
          if aws s3api head-bucket --bucket $LAMBDA_CODE_BUCKET > /dev/null 2>&1; then
            echo "Bucket $LAMBDA_CODE_BUCKET already exists. Skipping creation."
          else
            echo "Creating bucket $LAMBDA_CODE_BUCKET..."
            if [ "${{ secrets.AWS_REGION }}" = "us-east-1" ]; then
              aws s3api create-bucket --bucket $LAMBDA_CODE_BUCKET
            else
              aws s3api create-bucket \
                --bucket $LAMBDA_CODE_BUCKET \
                --region ${{ secrets.AWS_REGION }} \
                --create-bucket-configuration LocationConstraint=${{ secrets.AWS_REGION }}
            fi
          fi

      # Step 4: Verify Lambda Function Code Exists
      - name: Verify Lambda Function Code
        run: |
          if [ ! -f src/lambda_function.py ]; then
            echo "Error: Lambda function code (src/lambda_function.py) is missing."
            exit 1
          fi

      # Step 5: Zip Lambda Function Code
      - name: Zip Lambda Function Code
        run: |
          mkdir -p build
          zip -j build/lambda_function.zip src/lambda_function.py

      # Step 6: Upload Lambda Function Code to S3
      - name: Upload Lambda Function Code
        run: |
          LAMBDA_CODE_BUCKET="textract-lambda-code-bucket"
          LAMBDA_ZIP_FILE="build/lambda_function.zip"
          echo "Uploading Lambda function code to S3..."
          aws s3 cp $LAMBDA_ZIP_FILE s3://$LAMBDA_CODE_BUCKET/

      # Step 7: Deploy IAM Roles Stack
      - name: Deploy IAM Roles Stack
        run: |
          aws cloudformation deploy \
            --stack-name textract-iam-roles-stack \
            --template-file iam-roles.yaml \
            --capabilities CAPABILITY_NAMED_IAM

      # Step 8: Deploy CloudFormation Stack
      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --stack-name textract-stack \
            --template-file textract.yaml \
            --capabilities CAPABILITY_NAMED_IAM

      # Cleanup Step: Delete all AWS resources if the workflow fails
      - name: Cleanup AWS Resources
        if: failure()
        run: |
          echo "Cleaning up AWS resources..."

          # Delete the CloudFormation stack
          STACK_NAME="textract-stack"
          echo "Deleting CloudFormation stack $STACK_NAME..."
          aws cloudformation delete-stack --stack-name $STACK_NAME
          echo "Waiting for CloudFormation stack $STACK_NAME to be deleted..."
          aws cloudformation wait stack-delete-complete --stack-name $STACK_NAME || echo "Stack $STACK_NAME already deleted."

          # Delete the IAM roles stack
          IAM_STACK_NAME="textract-iam-roles-stack"
          echo "Deleting CloudFormation stack $IAM_STACK_NAME..."
          aws cloudformation delete-stack --stack-name $IAM_STACK_NAME
          echo "Waiting for CloudFormation stack $IAM_STACK_NAME to be deleted..."
          aws cloudformation wait stack-delete-complete --stack-name $IAM_STACK_NAME || echo "Stack $IAM_STACK_NAME already deleted."

          # Delete the Lambda code S3 bucket
          LAMBDA_CODE_BUCKET="textract-lambda-code-bucket"
          echo "Deleting S3 bucket $LAMBDA_CODE_BUCKET..."
          aws s3 rb s3://$LAMBDA_CODE_BUCKET --force || echo "Bucket $LAMBDA_CODE_BUCKET already deleted."

          echo "Cleanup completed."