name: AWS Textract Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy AWS Resources
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: Pre-cleanup
      - name: Pre-cleanup
        run: |
          echo "Cleaning up existing resources..."
          aws cloudformation delete-stack --stack-name textract-stack || echo "Stack already deleted."
          aws cloudformation delete-stack --stack-name textract-iam-roles-stack || echo "Stack already deleted."
          aws s3 rb s3://textract-lambda-code-bucket --force || echo "Bucket already deleted."

      # Step 4: Create S3 Bucket for Lambda Code
      - name: Create S3 Bucket for Lambda Code
        run: |
          LAMBDA_CODE_BUCKET="textract-lambda-code-bucket-${{ github.run_id }}"
          if aws s3api head-bucket --bucket $LAMBDA_CODE_BUCKET > /dev/null 2>&1; then
            echo "Bucket $LAMBDA_CODE_BUCKET already exists. Skipping creation."
          else
            echo "Creating bucket $LAMBDA_CODE_BUCKET..."
            aws s3api create-bucket \
              --bucket $LAMBDA_CODE_BUCKET \
              --region ${{ secrets.AWS_REGION }} \
              --create-bucket-configuration LocationConstraint=${{ secrets.AWS_REGION }}
          fi

      # Step 5: Verify Lambda Function Code Exists
      - name: Verify Lambda Function Code
        run: |
          if [ ! -f src/lambda_function.py ]; then
            echo "Error: Lambda function code (src/lambda_function.py) is missing."
            exit 1
          fi

      # Step 6: Zip Lambda Function Code
      - name: Zip Lambda Function Code
        run: |
          mkdir -p build
          zip -j build/lambda_function.zip src/lambda_function.py

      # Step 7: Upload Lambda Function Code to S3
      - name: Upload Lambda Function Code
        run: |
          LAMBDA_CODE_BUCKET="textract-lambda-code-bucket-${{ github.run_id }}"
          aws s3 cp build/lambda_function.zip s3://$LAMBDA_CODE_BUCKET/

      # Step 8: Deploy IAM Roles Stack
      - name: Deploy IAM Roles Stack
        run: |
          aws cloudformation deploy \
            --stack-name textract-iam-roles-stack \
            --template-file iam-roles.yaml \
            --capabilities CAPABILITY_NAMED_IAM

      # Step 9: Deploy CloudFormation Stack
      - name: Deploy CloudFormation Stack
        run: |
          LAMBDA_CODE_BUCKET="textract-lambda-code-bucket-${{ github.run_id }}"
          aws cloudformation deploy \
            --stack-name textract-stack \
            --template-file textract.yaml \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides LambdaCodeBucketName=$LAMBDA_CODE_BUCKET