name: Deploy S3

on:
  workflow_call:
    outputs:
      bucket_exists:
        description: "Whether buckets already exist"
        value: ${{ jobs.deploy.outputs.bucket_exists }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      bucket_exists: ${{ steps.check-bucket.outputs.exists }}
    env:
      LAMBDA_BUCKET: textract-lambda-code-bucket-2024
      SOURCE_BUCKET: textract-source-docs-2024

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Check S3 Buckets
        id: check-bucket
        run: |
          if aws s3api head-bucket --bucket ${LAMBDA_BUCKET} 2>/dev/null && \
             aws s3api head-bucket --bucket ${SOURCE_BUCKET} 2>/dev/null; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "Buckets already exist"
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "Creating buckets..."
            aws cloudformation deploy \
              --stack-name textract-s3-stack \
              --template-file templates/s3.yaml \
              --capabilities CAPABILITY_NAMED_IAM
          fi