name: Deploy Textract

on:
  workflow_call:
    inputs:
      bucket_name:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      LAMBDA_BUCKET: "textract-lambda-code-bucket-2024"
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Check Stack Status
        id: check-stack
        run: |
          if aws cloudformation describe-stacks --stack-name textract-stack 2>/dev/null; then
            STACK_STATUS=$(aws cloudformation describe-stacks --stack-name textract-stack --query 'Stacks[0].StackStatus' --output text)
            if [ "$STACK_STATUS" == "ROLLBACK_COMPLETE" ]; then
              echo "Deleting failed stack..."
              aws cloudformation delete-stack --stack-name textract-stack
              aws cloudformation wait stack-delete-complete --stack-name textract-stack
            fi
          fi

      - name: Package Lambda
        run: |
          mkdir -p build
          zip -j build/lambda_function.zip src/lambda_function.py

      - name: Upload Lambda
        run: |
          aws s3 cp build/lambda_function.zip s3://${LAMBDA_BUCKET}/lambda_function.zip

      - name: Deploy Stack
        run: |
          aws cloudformation deploy \
            --stack-name textract-stack \
            --template-file templates/textract.yaml \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides BucketName=${LAMBDA_BUCKET}

      - name: Cleanup
        if: always()
        run: rm -rf build/