name: AWS Textract Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy AWS Resources
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: Deploy IAM Roles Stack
      - name: Deploy IAM Roles Stack
        run: |
          aws cloudformation deploy \
            --stack-name textract-iam-roles-stack \
            --template-file iam-roles.yaml \
            --capabilities CAPABILITY_NAMED_IAM

      # Step 4: Deploy CloudFormation Stack
      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --stack-name textract-stack \
            --template-file textract.yaml \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides LambdaCodeBucketName=textract-lambda-code-bucket

      # Step 5: Wait for CloudFormation Stack to Complete
      - name: Wait for CloudFormation Stack
        run: |
          echo "Waiting for CloudFormation stack to complete..."
          aws cloudformation wait stack-create-complete --stack-name textract-stack
          echo "CloudFormation stack creation completed."

      # Step 6: Verify Lambda Function Code Exists
      - name: Verify Lambda Function Code
        run: |
          if [ ! -f src/lambda_function.py ]; then
            echo "Error: Lambda function code (src/lambda_function.py) is missing."
            exit 1
          fi

      # Step 7: Zip Lambda Function Code
      - name: Zip Lambda Function Code
        run: |
          mkdir -p build
          zip -j build/lambda_function.zip src/lambda_function.py

      # Step 8: Upload Lambda Function Code to Lambda
      - name: Upload Lambda Function Code to Lambda
        run: |
          echo "Uploading Lambda function code to Lambda..."
          aws lambda update-function-code \
            --function-name TextractFunction \
            --s3-bucket textract-lambda-code-bucket \
            --s3-key lambda_function.zip

      # Step 9: Cleanup Step (if workflow fails)
      - name: Cleanup AWS Resources
        if: failure()
        run: |
          echo "Cleaning up AWS resources..."

          # Delete the CloudFormation stack
          STACK_NAME="textract-stack"
          echo "Deleting CloudFormation stack $STACK_NAME..."
          aws cloudformation delete-stack --stack-name $STACK_NAME
          echo "Waiting for CloudFormation stack $STACK_NAME to be deleted..."
          aws cloudformation wait stack-delete-complete --stack-name $STACK_NAME || echo "Stack $STACK_NAME already deleted."

          # Delete the IAM roles stack
          IAM_STACK_NAME="textract-iam-roles-stack"
          echo "Deleting CloudFormation stack $IAM_STACK_NAME..."
          aws cloudformation delete-stack --stack-name $IAM_STACK_NAME
          echo "Waiting for CloudFormation stack $IAM_STACK_NAME to be deleted..."
          aws cloudformation wait stack-delete-complete --stack-name $IAM_STACK_NAME || echo "Stack $IAM_STACK_NAME already deleted."

          echo "Cleanup completed."