name: AWS Textract Workflow

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch
  workflow_dispatch:  # Allow manual triggering for delete services

jobs:
  deploy:
    name: Deploy AWS Resources
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: Upload Lambda Function Code to S3
      - name: Upload Lambda Function Code
        run: |
          LAMBDA_CODE_BUCKET="python-code-bucket-${{ secrets.AWS_ACCOUNT_ID }}-${{ secrets.AWS_REGION }}"
          LAMBDA_ZIP_FILE="lambda_function.zip"

          # Check if the S3 bucket exists
          if aws s3api head-bucket --bucket $LAMBDA_CODE_BUCKET > /dev/null 2>&1; then
            echo "Bucket $LAMBDA_CODE_BUCKET already exists. Skipping creation."
          else
            echo "Creating bucket $LAMBDA_CODE_BUCKET..."
            if [ "${{ secrets.AWS_REGION }}" = "us-east-1" ]; then
              aws s3api create-bucket --bucket $LAMBDA_CODE_BUCKET
            else
              aws s3api create-bucket \
                --bucket $LAMBDA_CODE_BUCKET \
                --region ${{ secrets.AWS_REGION }} \
                --create-bucket-configuration LocationConstraint=${{ secrets.AWS_REGION }}
            fi
          fi

          # Upload the Lambda function zip file to the S3 bucket
          echo "Uploading Lambda function code to S3..."
          aws s3 cp $LAMBDA_ZIP_FILE s3://$LAMBDA_CODE_BUCKET/

      # Step 4: Upload CloudFormation Template to S3
      - name: Upload CloudFormation Template
        run: |
          TEMPLATE_FILE="textract.yaml"
          TEMPLATE_BUCKET="cloudformation-templates-${{ secrets.AWS_ACCOUNT_ID }}-${{ secrets.AWS_REGION }}"

          # Check if the S3 bucket exists
          if aws s3api head-bucket --bucket $TEMPLATE_BUCKET > /dev/null 2>&1; then
            echo "Bucket $TEMPLATE_BUCKET already exists. Skipping creation."
          else
            echo "Creating bucket $TEMPLATE_BUCKET..."
            if [ "${{ secrets.AWS_REGION }}" = "us-east-1" ]; then
              aws s3api create-bucket --bucket $TEMPLATE_BUCKET
            else
              aws s3api create-bucket \
                --bucket $TEMPLATE_BUCKET \
                --region ${{ secrets.AWS_REGION }} \
                --create-bucket-configuration LocationConstraint=${{ secrets.AWS_REGION }}
            fi
          fi

          # Upload the CloudFormation template to the S3 bucket
          echo "Uploading CloudFormation template to S3..."
          aws s3 cp $TEMPLATE_FILE s3://$TEMPLATE_BUCKET/

      # Step 5: Deploy CloudFormation Stack
      - name: Deploy CloudFormation Stack
        run: |
          STACK_NAME="textract-stack"
          TEMPLATE_BUCKET="cloudformation-templates-${{ secrets.AWS_ACCOUNT_ID }}-${{ secrets.AWS_REGION }}"
          TEMPLATE_FILE="textract.yaml"

          # Deploy the CloudFormation stack
          aws cloudformation deploy \
            --stack-name $STACK_NAME \
            --template-file $TEMPLATE_FILE \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              LambdaCodeBucketName="python-code-bucket-${{ secrets.AWS_ACCOUNT_ID }}-${{ secrets.AWS_REGION }}" \
              TextractUploadBucketName="upload-textract-bucket-${{ secrets.AWS_ACCOUNT_ID }}-${{ secrets.AWS_REGION }}" \
              DynamoDBTableName="TextractData" \
              LambdaFunctionName="TextractFunction"

      # Step 6: Verify Deployment
      - name: Verify Deployment
        run: |
          echo "Verifying deployment..."
          aws cloudformation describe-stacks --stack-name textract-stack