name: Deploy Textract

on:
  workflow_call:
    inputs:
      bucket_name:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set account ID
        run: |
          echo "AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)" >> $GITHUB_ENV

      - name: Deploy Lambda code
        run: |
          mkdir -p build
          zip -j build/lambda_function.zip src/lambda_function.py
          aws s3 cp build/lambda_function.zip s3://${{ inputs.bucket_name }}/

      - name: Deploy Textract
        run: |
          aws cloudformation deploy \
            --stack-name textract-service \
            --template-file templates/textract.yaml \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              AccountId=${AWS_ACCOUNT_ID} \
              BucketName=${{ inputs.bucket_name }}