name: Deploy S3

on:
  workflow_call:
    inputs:
      bucket_name:
        required: true
        type: string
    outputs:
      bucket_exists:
        description: "Whether bucket already exists"
        value: ${{ jobs.deploy.outputs.bucket_exists }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      bucket_exists: ${{ steps.check-bucket.outputs.exists }}

    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Check S3 Bucket
        id: check-bucket
        run: |
          if aws s3api head-bucket --bucket ${{ inputs.bucket_name }} 2>/dev/null; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "Bucket already exists"
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "Creating bucket..."
            aws cloudformation deploy \
              --stack-name textract-s3-stack \
              --template-file templates/s3.yaml \
              --parameter-overrides BucketName=${{ inputs.bucket_name }}
          fi