name: Deploy S3 Infrastructure

on:
  workflow_dispatch:
  workflow_call:

jobs:
  deploy-s3:
    runs-on: ubuntu-latest
    outputs:
      bucket_name: ${{ steps.get-bucket.outputs.bucket_name }}

    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set AWS Account ID
        run: echo "AWS_ACCOUNT_ID=$(aws sts get-caller-identity --output text --query Account)" >> $GITHUB_ENV

      - name: Deploy S3 Stack
        run: |
          aws cloudformation deploy \
            --stack-name textract-s3-stack \
            --template-file templates/s3-bucket.yaml \
            --parameter-overrides AccountId=$AWS_ACCOUNT_ID

      - name: Get Bucket Name
        id: get-bucket
        run: |
          BUCKET_NAME="textract-lambda-code-bucket-$AWS_ACCOUNT_ID"
          echo "bucket_name=$BUCKET_NAME" >> $GITHUB_OUTPUT