name: Deploy Textract Services

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 3: Install or Update AWS CLI
      - name: Install or Update AWS CLI
        run: |
          if ! aws --version; then
            echo "AWS CLI not found. Installing..."
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
          else
            echo "AWS CLI found. Updating..."
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install --update
          aws --version

      # Step 4: Deploy CloudFormation Stack
      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --stack-name textract-stack \
            --template-file textract.yaml \
            --capabilities CAPABILITY_NAMED_IAM

      # Step 5: Wait for CloudFormation Stack to Complete
      - name: Wait for CloudFormation Stack
        run: |
          echo "Waiting for CloudFormation stack to complete..."
          if ! aws cloudformation wait stack-create-complete --stack-name textract-stack; then
            echo "Error: CloudFormation stack creation failed."
            aws cloudformation describe-stack-events --stack-name textract-stack
            exit 1
          fi
          echo "CloudFormation stack creation completed."

      # Step 6: Verify Lambda Function Code Exists
      - name: Verify Lambda Function Code
        run: |
          if [ ! -f src/lambda_function.py ]; then
            echo "Error: Lambda function code (src/lambda_function.py) is missing."
            exit 1
          fi

      # Step 7: Zip Lambda Function Code
      - name: Zip Lambda Function Code
        run: |
          mkdir -p build
          zip -j build/lambda_function.zip src/lambda_function.py

      # Step 8: Upload Lambda Function Code to S3
      - name: Upload Lambda Function Code to S3
        run: |
          aws s3 cp build/lambda_function.zip s3://textract-lambda-code-bucket/lambda_function.zip

      # Step 9: Cleanup Resources on Failure
      - name: Cleanup Resources
        if: failure()
        run: |
          echo "Cleaning up resources due to workflow failure..."
          aws cloudformation delete-stack --stack-name textract-stack
          echo "Waiting for stack deletion to complete..."
          aws cloudformation wait stack-delete-complete --stack-name textract-stack
          echo "Stack deletion completed."