name: Main Deployment Orchestrator

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  validate-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Validate Templates
        run: |
          aws cloudformation validate-template --template-body file://templates/s3.yaml
          aws cloudformation validate-template --template-body file://templates/textract.yaml

  deploy-s3:
    needs: validate-env
    uses: ./.github/workflows/deploy-s3.yml
    secrets: inherit

  deploy-textract:
    needs: [validate-env, deploy-s3]
    uses: ./.github/workflows/deploy-textract.yml
    with:
      bucket_name: textract-lambda-code-bucket-2025
    secrets: inherit